name: Build
on: [push, pull_request]

jobs:
  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run make
